# Generated by Django 3.1.7 on 2021-03-12 18:07

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210312_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='code',
            field=models.CharField(default=utils.utils.generate_uniq_code, max_length=32),
        ),
    ]
